"""ajuste tamaño de las empresas y usuario

Revision ID: 5ed2e4505c1c
Revises: 
Create Date: 2025-09-27 23:53:04.242013

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5ed2e4505c1c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.alter_column('nombre_empresa',
               existing_type=mysql.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('rfc',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=13),
               existing_nullable=True)
        batch_op.alter_column('direccion',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('telefono',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=10),
               existing_nullable=True)

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('contraseña',
               existing_type=mysql.VARCHAR(length=1000),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('contraseña',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=1000),
               existing_nullable=False)
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.alter_column('telefono',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('direccion',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('rfc',
               existing_type=sa.String(length=13),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('nombre_empresa',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=150),
               existing_nullable=True)

    # ### end Alembic commands ###
